[tool.poetry]
name = "steganossaurus"
version = "0.1.0"
description = ""
authors = ["João Vitor Maia <maia.tostring@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
pycryptodome = "^3.19.0"
black = "^23.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
